# Generated by Django 6.0.2 on 2026-02-04 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_module_group_subject_module_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')])),
                ('time', models.TimeField(help_text='Время начала занятия')),
                ('subject', models.CharField(help_text='Предмет', max_length=200)),
                ('room', models.CharField(blank=True, help_text='Кабинет/аудитория', max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.studygroup')),
            ],
            options={
                'ordering': ['day_of_week', 'time'],
                'unique_together': {('group', 'day_of_week', 'time')},
            },
        ),
    ]
