# Generated by Django 6.0.2 on 2026-02-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='attempts_limit',
            field=models.IntegerField(default=3, help_text='Максимальное количество попыток на прохождение теста'),
        ),
    ]
